directories:
  artifact_dir: "artifacts"
  raw_dir: "raw"


files:
  local_data_file: artifacts/raw/data.zip
  base_model_file: artifacts/models/base_model.h5
  updated_base_model_file: artifacts/models/base_model_updated.h5
  trained_model_file: artifacts/models/training/trained_model.h5




data_ingestion:
  source_url: "https://drive.google.com/file/d/1z0mreUtRmR-P-magILsDR3T7M6IkGXtY/view?usp=sharing"


data_processing:  
  image_size: [224,224,3]
  batch_size: 16
  include_top: False
  epoch: 1
  classes: 2
  weights: imagenet
  learning_rate: 0.01
  augmentation: True

training:
  training_data_dir: artifacts/raw/Chest-CT-Scan-data

